{% set name = "lcls2_timetool" %}
{% set version = "3.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url:  https://pswww.slac.stanford.edu/swdoc/tutorials/{{ name }}-{{ version }}.tar.gz
  sha256: 6887e32827ec9b4d73464dcfbbd0eb3f51ec4698e0c8a6b0c6a05b6c010b1646
  patches:
    - pip.patch

build:
  skip: True  # [win or osx]
  noarch: python
  number: 15
  script:
    - "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - setuptools
    - pip
  run:
    - python

about:
  home: https://github.com/slaclab/lcls2-timetool
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'LCLS-II timetool software and firmware'
  description: |
    firmware for LCLS-II timetool devices.
  doc_url: https://github.com/slaclab/lcls2-timetool
  dev_url: https://github.com/slaclab/lcls2-timetool

extra:
  recipe-maintainers:
    - valmar
    - chrisvam

